In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:

#recupere les données de Data_Arbre.csv
data = pd.read_csv("Data_Arbre.csv")

print(data.head(5))


   longitude   latitude              clc_quartier             clc_secteur  \
0   3.293264  49.840500  Quartier du Centre-Ville             Quai Gayant   
1   3.273380  49.861409    Quartier du Vermandois              Stade Cepy   
2   3.289068  49.844513  Quartier du Centre-Ville   Rue Villebois Mareuil   
3   3.302387  49.861778      Quartier de l'Europe  Square des Marronniers   
4   3.304047  49.858446      Quartier de l'Europe           Avenue Buffon   

   haut_tot  haut_tronc  tronc_diam fk_arb_etat fk_stadedev     fk_port  \
0       6.0         2.0        37.0    EN PLACE       Jeune  semi libre   
1      13.0         1.0       160.0    EN PLACE      Adulte  semi libre   
2      12.0         3.0       116.0    REMPLACÉ      Adulte  semi libre   
3      16.0         3.0       150.0    EN PLACE      Adulte  semi libre   
4       5.0         2.0       170.0    Essouché      Adulte      réduit   

  fk_pied fk_situation fk_revetement  age_estim  fk_prec_estim  clc_nbr_diag  \
0   ga

In [3]:
#sépare les données en deux dataframes, un pour les X et un pour les Y, les X sont la colonne age_estim, et les Y sont les colonnes tronc_diam  + haut_tronc + clc_nbr_diag 
Y = data[['age_estim']]

X = data[['tronc_diam','haut_tronc', 'haut_tot', 'clc_nbr_diag', 'fk_stadedev', 'fk_nomtech']]

print(Y.head(5))    


   age_estim
0       15.0
1       50.0
2       30.0
3       50.0
4       40.0


In [4]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import LabelEncoder
encoder = OrdinalEncoder()
#encoder permet de transformer les valeurs de la colonne en valeurs numériques (ordonnees)
label = LabelEncoder()
#label permet de transformer les valeurs de la colonne en valeurs numériques


X['fk_stadedev'] = encoder.fit_transform(X[['fk_stadedev']])
X['fk_nomtech'] = label.fit_transform(X[['fk_nomtech']])
# X['feuillage'] = encoder.fit_transform(X[['feuillage']])
# print(X['feuillage'].head(5))

C:\Users\alexm\AppData\Local\Temp\ipykernel_4388\1827100589.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['fk_stadedev'] = encoder.fit_transform(X[['fk_stadedev']])
C:\Users\alexm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\alexm\AppData\Local\Temp\ipykernel_4388\1827100589.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

Se

encoder permet de transformer les valeurs de la colonne en valeurs numériques

In [5]:
from sklearn.preprocessing import StandardScaler
scaler_X = StandardScaler()
scaler_Y = StandardScaler()

X = scaler_X.fit_transform(X)
Y = scaler_Y.fit_transform(Y)
print(X.shape, Y.shape)

(7409, 6) (7409, 1)


Scaler réduit remarquablement les scores RMSE et MAE

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import train_test_split
import pickle


indices = np.arange(X.shape[0])
X_train, X_test, Y_train, Y_test, indices_train, indices_test = train_test_split(X, Y, indices, test_size=0.2, random_state=42)

print("Indices des lignes dans X_test:", indices_test)
print("Indices des lignes dans X:", indices)

data_test = data.iloc[indices_test]

data_test.to_json('Data_Arbre_test.json', orient='records')

print(data_test["age_estim"].tail(10))

print(X_test)







Indices des lignes dans X_test: [7092 1544 2431 ... 4139 6203 4393]
Indices des lignes dans X: [   0    1    2 ... 7406 7407 7408]
438     30.0
3320    35.0
3937    40.0
434     30.0
751     50.0
1488    50.0
1593    50.0
4139    60.0
6203    30.0
4393    30.0
Name: age_estim, dtype: float64
[[ 0.12165495  1.21102921  1.02314578 -0.27980404 -0.56224657  1.5375964 ]
 [-0.33570685 -0.46555    -0.59694528 -0.27980404 -0.56224657 -1.0182212 ]
 [ 0.9347426  -1.02440973  0.53711846 -0.27980404 -0.56224657 -0.95878358]
 ...
 [-0.08161696  0.09330974  1.83319131 -0.27980404 -0.56224657 -1.28569048]
 [ 1.44292238 -0.74497987 -0.59694528 -0.27980404 -0.56224657 -0.78047072]
 [ 0.34186619 -0.46555    -0.43493618 -0.27980404 -0.56224657  0.86892319]]


In [7]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score

Grid Search pour RandomForestRegressor

In [ ]:
# forest = RandomForestRegressor()

# param_grid = {
#     'n_estimators': [200,300,400],
#     'max_depth' : [10,15,20],
#     'min_samples_split': [2,3],
#     'min_samples_leaf': [1, 2],
#     'max_samples': [0.6, 0.7, 0.8,0.9, 1]
# }

# grid_search = GridSearchCV(estimator=forest, param_grid=param_grid, cv=5, n_jobs=-1, verbose=2, scoring='neg_mean_squared_error')
# grid_search.fit(X_train, Y_train)
# best_model = grid_search.best_estimator_
# print('best params :', grid_search.best_params_)


# # best params : {'max_depth': 15, 'max_samples': 0.8, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 400}
# # 


Fitting 5 folds for each of 180 candidates, totalling 900 fits


c:\Users\mbell\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


best params : {'max_depth': 15, 'max_samples': 0.8, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 400}


In [8]:

random_forest = RandomForestRegressor(max_depth= 15, min_samples_leaf= 1, min_samples_split= 2, 
                                         n_estimators= 400, max_samples=0.8, max_features="log2", random_state=42)

random_forest.fit(X_train, Y_train)

Y_pred = random_forest.predict(X_test)

mse = mean_squared_error(Y_test, Y_pred)
rmse = np.sqrt(mse)

r2_score_forest = r2_score(Y_test, Y_pred)
mae = mean_absolute_error(Y_test, Y_pred)

cross_val_score_forest = cross_val_score(random_forest, X_test, Y_test, cv=5).mean()

print("R2 score du modèle de régression linéaire :", r2_score_forest)
print("RMSE du modèle de régression linéaire :", rmse)
print("MAE du modèle de régression linéaire :", mae)
# print("Cross val score du modèle de régression linéaire :", cross_val_score_forest)


C:\Users\alexm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\alexm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\alexm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y 

R2 score du modèle de régression linéaire : 0.8181589076193863
RMSE du modèle de régression linéaire : 0.4260740869260982
MAE du modèle de régression linéaire : 0.25305225751731947


#CART : Classification And Regression Tree

Grid Search pour CART : 
Le DecisionTreeRegressor est une implémentation de l'algorithme CART (Classification And Regression Tree) pour les problèmes de régression
C'est un arbre qui va diviser l'ensemble des données, en sous-ensemble, et le refaire plusieurs fois

Au début, la racine contient l'ensemble des données
Pour chaque caractéristique, l'algorithme cherche le meilleur point de division (seuil) qui divise les données en deux sous-ensembles de manière à réduire au maximum l'erreur de régression.
L'erreur de régression est souvent mesurée par le MSE (Mean Squared Error) ou le MAE (Mean Absolute Error). Le but est de minimiser cette erreur dans les sous-ensembles qui sont créés.

Quand on a trouvé le meilleur point de division, on divise les données en 2 sous-ensemble à partir de ce point.

On répète la même méthode sur chaque sous-ensemble

Chaque noeud de l'arbre représente une condition sur une caractéristique et un seuil, et chaque feuille représente une prédiction de la valeur cible.

On s'arrête quand on a atteint une des conditions d'arrêt (profondeure maximale, nombre d'échantillons dans un noeud inférieur à un seuil minimum, si on ne réduit plus l'erreur de régression)

In [9]:
from sklearn.tree import DecisionTreeRegressor

Explication des hyperparametres du grid search :

max_depth : profondeur maximale de l'arbre, peut réduire le risque de surapprentissage.
min_samples_split : Le nombre minimum d'échantillons requis pour diviser un noeud interne.
min_samples_leaf : nombre minimum d'échantillons requis pour être à un noeud feuille.

In [ ]:
# #grid search pour trouver les meilleurs paramètres de decision tree regressor
# param_grid = {
#     'max_depth' : [7,8,9,10,11,12,13],
#     'min_samples_split': [2,3,4,5,6,7,8],
#     'min_samples_leaf': [1, 2, 3, 4]
# }

# grid_search = GridSearchCV(estimator=DecisionTreeRegressor(), param_grid=param_grid, cv=5, n_jobs=-1, verbose=2, scoring='neg_mean_squared_error')
# grid_search.fit(X_train, Y_train)
# best_model = grid_search.best_estimator_

# print('best params :', grid_search.best_params_)
# #best params : {'max_depth': 10, 'min_samples_leaf': 3, 'min_samples_split': 4}

Fitting 5 folds for each of 196 candidates, totalling 980 fits
best params : {'max_depth': 10, 'min_samples_leaf': 3, 'min_samples_split': 3}


In [10]:
best_model_found = DecisionTreeRegressor(max_depth= 10, min_samples_leaf= 3, min_samples_split= 4)

tree = best_model_found
tree.fit(X_train, Y_train)
Y_pred = tree.predict(X_test)

mse = mean_squared_error(Y_test, Y_pred)
rmse = np.sqrt(mse)
mae = mean_absolute_error(Y_test, Y_pred)
r2_scoreee = r2_score(Y_test, Y_pred)

cross_val_score_tree = cross_val_score(tree, X_test, Y_test, cv=5).mean()

print("R2 score du modèle de régression linéaire :", r2_scoreee)
print("RMSE du modèle de régression linéaire :", rmse)
print("MAE du modèle de régression linéaire :", mae)
print("Cross val score du modèle de régression linéaire :", cross_val_score_tree)

R2 score du modèle de régression linéaire : 0.7535262261307794
RMSE du modèle de régression linéaire : 0.49604886874262627
MAE du modèle de régression linéaire : 0.29687267492271835
Cross val score du modèle de régression linéaire : 0.6440786756106726


methode 3 : Réseau de neurones 

In [11]:
from sklearn.neural_network import MLPRegressor

Grid search pour réseau de neurones

In [ ]:
# grid search pour trouver les meilleurs paramètres de MLPRegressor
# param_grid : dictionnaire contenant les différentes combinaisons de paramètres à tester
# 'hidden_layer_sizes' : liste des différentes architectures de couches cachées à tester
# 'activation' : liste des différentes fonctions d'activation à tester
# 'solver' : liste des différents solveurs à tester
# 'alpha' : liste des différents paramètres de régularisation à tester
# 'learning_rate' : liste des différents taux d'apprentissage à tester

# param_grid={
#     'hidden_layer_sizes': [(50,50,50), (50,100,50), (100,100)],
#     'activation': ['tanh', 'relu'],
#     'solver': ['sgd', 'adam'],
#     'alpha': [0.0001, 0.05],
#     'learning_rate': ['constant','adaptive'],
# }

# grid_search = GridSearchCV(estimator=MLPRegressor(), param_grid=param_grid, cv=5, n_jobs=-1, verbose=2, scoring='neg_mean_squared_error')
# grid_search.fit(X_train, Y_train)

# best_model = grid_search.best_estimator_

# print('best params :', grid_search.best_params_)

# #best params : {'activation': 'relu', 'alpha': 0.05, 'hidden_layer_sizes': (100, 100), 'learning_rate': 'adaptive', 'solver': 'adam'}

Fitting 5 folds for each of 48 candidates, totalling 240 fits


c:\Users\mbell\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1631: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


best params : {'activation': 'relu', 'alpha': 0.05, 'hidden_layer_sizes': (100, 100), 'learning_rate': 'adaptive', 'solver': 'adam'}


In [12]:

best_model_found = MLPRegressor(hidden_layer_sizes=(24, 48), activation='relu', alpha=0.05, learning_rate='adaptive', solver='adam', max_iter=1000)
mlp = best_model_found
mlp.fit(X_train, Y_train)

Y_pred = mlp.predict(X_test)

mse = mean_squared_error(Y_test, Y_pred)
rmse = np.sqrt(mse)
mae = mean_absolute_error(Y_test, Y_pred)
r2_score_mlp = r2_score(Y_test, Y_pred)

cross_val_score_mlp = cross_val_score(mlp, X_test, Y_test, cv=5).mean()

print("R2 score du modèle de régression linéaire :", r2_score_mlp)
print("RMSE du modèle de régression linéaire :", rmse)
print("MAE du modèle de régression linéaire :", mae)
print("Cross val score du modèle de régression linéaire :", cross_val_score_mlp)

C:\Users\alexm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1631: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\alexm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1631: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\alexm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1631: DataConversionWarning: A column-vector y

R2 score du modèle de régression linéaire : 0.7614002920266387
RMSE du modèle de régression linéaire : 0.4880609489988986
MAE du modèle de régression linéaire : 0.32594839593380465
Cross val score du modèle de régression linéaire : 0.7009214306870944


KNeighborsRegressor

In [13]:
from sklearn.neighbors import KNeighborsRegressor

Grid search

In [ ]:
# #grid search pour trouver les meilleurs paramètres de KNeighborsRegressor
# param_grid = {
#     'n_neighbors': [9,10,11,12,13,14,15],
#     'weights': ['uniform', 'distance'],
#     'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
#     'leaf_size': [10,20,30,40,50]
# }

# grid_search = GridSearchCV(estimator=KNeighborsRegressor(), param_grid=param_grid, cv=5, n_jobs=-1, verbose=2, scoring='neg_mean_squared_error')
# grid_search.fit(X_train, Y_train)

# best_model = grid_search.best_estimator_

# print('best params :', grid_search.best_params_)

# #best params : {'algorithm': 'ball_tree', 'leaf_size': 20, 'n_neighbors': 10, 'weights': 'distance'}

Fitting 5 folds for each of 280 candidates, totalling 1400 fits
best params : {'algorithm': 'ball_tree', 'leaf_size': 20, 'n_neighbors': 10, 'weights': 'distance'}


In [14]:

best_model_found = KNeighborsRegressor(n_neighbors=10, weights='distance', algorithm='ball_tree', leaf_size=20)

knn = best_model_found
knn.fit(X_train, Y_train)

Y_pred = knn.predict(X_test)

mse = mean_squared_error(Y_test, Y_pred)
rmse = np.sqrt(mse)
mae = mean_absolute_error(Y_test, Y_pred)
r2_score_knn = r2_score(Y_test, Y_pred)

cross_val_score_knn = cross_val_score(knn, X_test, Y_test, cv=5).mean()

print("R2 score du modèle de régression linéaire :", r2_score_knn)
print("RMSE du modèle de régression linéaire :", rmse)
print("MAE du modèle de régression linéaire :", mae)
print("Cross val score du modèle de régression linéaire :", cross_val_score_knn)

R2 score du modèle de régression linéaire : 0.7848117216516649
RMSE du modèle de régression linéaire : 0.46349858389209364
MAE du modèle de régression linéaire : 0.2578538355544143
Cross val score du modèle de régression linéaire : 0.7085339410672501


Modele 5 : HistGrandiantBoosting

Grid Search pour HistGrandientBoosting

In [15]:
from sklearn.ensemble import HistGradientBoostingRegressor

In [496]:
# #grid search pour trouver les meilleurs paramètres de HistGradientBoostingRegressor

# param_grid = {
#     'max_iter': [200,300,400,500],
#     'max_leaf_nodes': [31, 41, 51],
#     'learning_rate': [0.1, 0.2, 0.3],
#     'max_depth': [10, 15, 20]
# }

# grid_search = GridSearchCV(estimator=HistGradientBoostingRegressor(), param_grid=param_grid, cv=5, n_jobs=-1, verbose=2, scoring='neg_mean_squared_error')
# grid_search.fit(X_train, Y_train)

# best_model = grid_search.best_estimator_

# print('best params :', grid_search.best_params_)

Fitting 5 folds for each of 108 candidates, totalling 540 fits


c:\Users\mbell\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1310: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


best params : {'learning_rate': 0.1, 'max_depth': 15, 'max_iter': 500, 'max_leaf_nodes': 31}


In [16]:

hist = HistGradientBoostingRegressor(learning_rate= 0.1, max_depth = 15, max_iter = 300, max_leaf_nodes = 31, random_state=42)
hist.fit(X_train, Y_train)

Y_pred = hist.predict(X_test)

mse = mean_squared_error(Y_test, Y_pred)
rmse = np.sqrt(mse)
mae = mean_absolute_error(Y_test, Y_pred)
r2_score_hist = r2_score(Y_test, Y_pred)

cross_val_score_hist = cross_val_score(hist, X_test, Y_test, cv=5).mean()

print("R2 score du modèle de régression linéaire :", r2_score_hist)
print("RMSE du modèle de régression linéaire :", rmse)
print("MAE du modèle de régression linéaire :", mae)
print("Cross val score du modèle de régression linéaire :", cross_val_score_hist)

C:\Users\alexm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\utils\validation.py:1310: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\alexm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\joblib\externals\loky\backend\context.py:136: UserWarning: Could not find the number of physical cores for the following reason:
found 0 physical cores < 1
Returning the number of logical cores instead. You can silence this warning by setting LOKY_MAX_CPU_COUNT to the number of cores you want to use.
  warnings.warn(
  File "C:\Users\alexm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\joblib\externals\loky\backend\con

R2 score du modèle de régression linéaire : 0.8079655948978623
RMSE du modèle de régression linéaire : 0.43785330109940146
MAE du modèle de régression linéaire : 0.26822405515355563
Cross val score du modèle de régression linéaire : 0.7263892763502553


On met les modèles en .pkl

In [17]:
import pickle

dict_pickle = {
    'ordinal' : encoder,
    'label' : label,
    'scaler_X' : scaler_X,
    'scaler_Y' : scaler_Y,
    'RandomForest': random_forest,
    'DecisionTree': tree,
    'MLP': mlp,
    'KNN': knn,
    'Hist': hist
}

# Sauvegarder le modèle dans un fichier .pkl
with open('dict.pkl', 'wb') as file:
    pickle.dump(dict_pickle, file)

Test d'ouverture de nos fichiers .pkl

In [18]:

with open('dict.pkl', 'rb') as file:
    pkl_dict = pickle.load(file)


model = pkl_dict['RandomForest']

Y_pred = model.predict(X_test)

mse = mean_squared_error(Y_test, Y_pred)
rmse = np.sqrt(mse)
mae = mean_absolute_error(Y_test, Y_pred)
r2_score_model = r2_score(Y_test, Y_pred)

# cross_val_score_hist = cross_val_score(model, X_test, Y_test, cv=5).mean()

print("R2 score du modèle de régression linéaire :", r2_score_model)
print("RMSE du modèle de régression linéaire :", rmse)
print("MAE du modèle de régression linéaire :", mae)
# print("Cross val score du modèle de régression linéaire :", cross_val_score_hist)

R2 score du modèle de régression linéaire : 0.8181589076193863
RMSE du modèle de régression linéaire : 0.4260740869260982
MAE du modèle de régression linéaire : 0.25305225751731947


Création du fichier JSON

In [179]:
# data_test = data.iloc[indices_test]

# data_test.to_json('Data_Arbre_test.json', orient='records')

# print(data_test["age_estim"].tail(10))


438     30.0
3320    35.0
3937    40.0
434     30.0
751     50.0
1488    50.0
1593    50.0
4139    60.0
6203    30.0
4393    30.0
Name: age_estim, dtype: float64


TESTS DE MON SCRIPT

In [19]:
with open('dict.pkl', 'rb') as file:
    pkl_dict_load = pickle.load(file)

scaler_X = pkl_dict_load['scaler_X']
scaler_Y = pkl_dict_load['scaler_Y']
model = pkl_dict_load['RandomForest']
ordinal = pkl_dict_load['ordinal']
label = pkl_dict_load['label']

print(scaler_X)
print(scaler_Y)
print(model)
print(ordinal)
print(label)

X = data_test[['haut_tronc','tronc_diam','fk_stadedev','clc_nbr_diag','fk_nomtech','haut_tot']]

X['fk_stadedev'] = pkl_dict_load['ordinal'].fit_transform(X[['fk_stadedev']])
X['fk_nomtech'] = pkl_dict_load['label'].fit_transform(X[['fk_nomtech']])
y_test = data_test['age_estim']

X = pkl_dict_load['scaler_X'].fit_transform(X)

print(X)


pred = pkl_dict_load['RandomForest'].predict(X) 

pred = pred.reshape(-1, 1)

# y_test_scaled = scaler_Y.transform(y_test.values.reshape(-1, 1))

pred = pkl_dict_load['scaler_Y'].inverse_transform(pred)

r2_score_model = r2_score(y_test, pred)
print("r2_score = ", r2_score_model)


StandardScaler()
StandardScaler()
RandomForestRegressor(max_depth=15, max_features='log2', max_samples=0.8,
                      n_estimators=400, random_state=42)
OrdinalEncoder()
LabelEncoder()
[[ 1.18379275  0.13637661 -0.55988451 -0.29322258  1.53691341  1.06471625]
 [-0.44619807 -0.3225397  -0.55988451 -0.29322258 -1.01116019 -0.59746587]
 [-0.98952835  0.95222783 -0.55988451 -0.29322258 -0.96168303  0.56606162]
 ...
 [ 0.0971322  -0.06758619 -0.55988451 -0.29322258 -1.30802314  1.89580731]
 [-0.71786321  1.46213485 -0.55988451 -0.29322258 -0.73903583 -0.59746587]
 [-0.44619807  0.35733632 -0.55988451 -0.29322258  0.77001747 -0.43124765]]
r2_score =  0.27214094856223514


C:\Users\alexm\AppData\Local\Temp\ipykernel_4388\2831851170.py:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['fk_stadedev'] = pkl_dict_load['ordinal'].fit_transform(X[['fk_stadedev']])
C:\Users\alexm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\alexm\AppData\Local\Temp\ipykernel_4388\2831851170.py:19: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] =

CART from scratch